name: thatraynerlad
favicon: null
layout_spectrum: 0.25253
typography_spectrum: 0.9593443106859922
title: thatraynerlad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fcc34f'
    - '#8a3c00'
    - '#371f15'
  brandStrength: 0.5625
  lightness: 0.6023389766924083
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
